import Foundation
import CryptoKit

/// One clipboard entry, in the form it is stored: text as UTF-8, an image as PNG bytes.
public enum ClipboardClip: Sendable, Equatable {
    case text(String)
    case image(Data)
}

/// THE CLIPBOARD HISTORY IS A FOLDER OF ORDINARY FILES.
///
/// Every clipboard change the monitor accepts becomes one `.txt` or `.png` here, and the folder is
/// an indexed root like any other. Search, filters, the folder browser, thumbnails, Quick Look and
/// deletion are the existing pipeline; nothing in the store knows a clip from a document. The
/// pasteboard itself holds only the latest item, so history has to be persisted somewhere, and a
/// file is the one form every part of the app can already read.
///
/// NAMES CARRY THE TIME. `2026-09-29 19.33.02 first words.txt`: sortable, so name order is copy
/// order, and the leading words make the filename search useful for text clips.
///
/// THE SAME CONTENT IS ONE FILE. A clip identical to one already stored renames that file to the
/// current time instead of writing a second copy, so it rises to the top of the folder. The rename
/// reaches the index as a move, which content addressing answers without a forward pass. The digest
/// is kept in an extended attribute, so finding a duplicate reads no file contents.
public final class ClipboardHistory: @unchecked Sendable {
    public let directory: URL
    private let lock = NSLock()
    /// Content digest -> file name, built from the extended attributes on first use.
    private var byDigest: [String: String]?

    /// Text beyond this is cut: it is what the extractor reads from any text file.
    public static let maxTextBytes = FileExtractor.maxTextBytes
    /// Images larger than this are not stored.
    public static let maxImageBytes = 50_000_000
    static let digestAttribute = "io.hanxiao.omni.clip"

    public init(directory: URL) { self.directory = directory }

    // MARK: - What is never recorded

    /// Pasteboard types that mark an item as not for history (nspasteboard.org): password
    /// managers set the concealed type on a copied secret, and transient or generated items are
    /// by definition not something the user copied to keep.
    /// Marks a copy Omni made itself (see OmniPasteboard in the app).
    public static let ownType = "io.hanxiao.omni.own"

    public static let skippedTypes: Set<String> = [
        ownType,
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    public static func shouldSkip(types: [String]) -> Bool {
        types.contains { skippedTypes.contains($0) }
    }

    // MARK: - Writing

    /// Store `clip` at `date`. Returns the file now holding it, or nil when there is nothing to
    /// store (whitespace-only text, an empty or oversized image).
    @discardableResult
    public func save(_ clip: ClipboardClip, at date: Date = Date()) throws -> URL? {
        guard let (data, ext, title) = Self.payload(clip) else { return nil }
        let digest = Self.digest(data)
        lock.lock(); defer { lock.unlock() }
        let fm = FileManager.default
        try fm.createDirectory(at: directory, withIntermediateDirectories: true)
        var map = loadDigestsLocked()
        let name = Self.fileName(date: date, title: title, ext: ext)

        if let existing = map[digest] {
            let from = directory.appendingPathComponent(existing)
            if existing == name, fm.fileExists(atPath: from.path) {
                try? fm.setAttributes([.modificationDate: date], ofItemAtPath: from.path)
                return from
            }
            if fm.fileExists(atPath: from.path) {
                let target = uniqueURLLocked(name)
                try fm.moveItem(at: from, to: target)
                try? fm.setAttributes([.modificationDate: date], ofItemAtPath: target.path)
                map[digest] = target.lastPathComponent
                byDigest = map
                return target
            }
        }
        let target = uniqueURLLocked(name)
        // Written under a hidden name and renamed into place: the crawl skips dot files, so the
        // indexer never reads a half-written clip.
        let temp = directory.appendingPathComponent(".\(UUID().uuidString).\(ext)")
        try data.write(to: temp)
        Self.setDigest(digest, at: temp)
        try? fm.setAttributes([.modificationDate: date], ofItemAtPath: temp.path)
        try fm.moveItem(at: temp, to: target)
        map[digest] = target.lastPathComponent
        byDigest = map
        return target
    }

    /// The file already holding `clip`, if one does. Reads no file contents: the digest is in the
    /// extended attributes.
    public func existingFile(for clip: ClipboardClip) -> URL? {
        guard let (data, _, _) = Self.payload(clip) else { return nil }
        let digest = Self.digest(data)
        lock.lock(); defer { lock.unlock() }
        guard let name = loadDigestsLocked()[digest] else { return nil }
        let url = directory.appendingPathComponent(name)
        return FileManager.default.fileExists(atPath: url.path) ? url : nil
    }

    // MARK: - Removing

    /// Delete clips last copied before `days` days ago. Returns how many were deleted. Zero or
    /// less keeps everything.
    @discardableResult
    public func prune(olderThanDays days: Int, now: Date = Date()) -> Int {
        guard days > 0 else { return 0 }
        let cutoff = now.addingTimeInterval(-Double(days) * 86_400)
        lock.lock(); defer { lock.unlock() }
        var removed = 0
        for url in entriesLocked(includeHidden: true) {
            let mtime = (try? url.resourceValues(forKeys: [.contentModificationDateKey]))?.contentModificationDate
            if let mtime, mtime < cutoff, (try? FileManager.default.removeItem(at: url)) != nil { removed += 1 }
        }
        if removed > 0 { byDigest = nil }
        return removed
    }

    /// Delete every clip and the folder itself.
    public func clear() throws {
        lock.lock(); defer { lock.unlock() }
        byDigest = nil
        guard FileManager.default.fileExists(atPath: directory.path) else { return }
        try FileManager.default.removeItem(at: directory)
    }

    /// How many clips are stored.
    public var count: Int {
        lock.lock(); defer { lock.unlock() }
        return entriesLocked(includeHidden: false).count
    }

    // MARK: - Naming

    private static let stamp: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyy-MM-dd HH.mm.ss"
        return f
    }()

    /// `2026-09-29 19.33.02 first words.txt`. The title is the first line of text, reduced to
    /// characters every file system accepts and cut at a word near 40 characters.
    static func fileName(date: Date, title: String, ext: String) -> String {
        let s = stamp.string(from: date)
        return title.isEmpty ? "\(s).\(ext)" : "\(s) \(title).\(ext)"
    }

    static func title(for text: String) -> String {
        let firstLine = text.split(whereSeparator: \.isNewline)
            .first { !$0.trimmingCharacters(in: .whitespaces).isEmpty } ?? ""
        var t = ""
        var lastWasSpace = true
        for ch in firstLine {
            if ch.unicodeScalars.contains(where: { $0.properties.generalCategory == .control }) { continue }
            // A separator becomes a space, not nothing: a copied URL reads "https example.com report"
            // rather than "httpsexample.comreport".
            if ch.isWhitespace || ch == "/" || ch == ":" || ch == "\\" {
                if !lastWasSpace { t.append(" ") }
                lastWasSpace = true
            } else {
                t.append(ch)
                lastWasSpace = false
            }
        }
        t = t.trimmingCharacters(in: .whitespaces)
        while t.hasPrefix(".") { t.removeFirst() }
        let limit = 40
        guard t.count > limit else { return t }
        let cut = String(t.prefix(limit))
        if let space = cut.lastIndex(of: " "), cut.distance(from: cut.startIndex, to: space) >= limit / 2 {
            return String(cut[..<space])
        }
        return cut
    }

    // MARK: - Internals

    private static func payload(_ clip: ClipboardClip) -> (Data, String, String)? {
        switch clip {
        case .text(let s):
            guard !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
            var data = Data(s.utf8)
            if data.count > maxTextBytes {
                // Cut on a character boundary so the file stays valid UTF-8.
                var cut = String(decoding: data.prefix(maxTextBytes), as: UTF8.self)
                if cut.last == "\u{FFFD}" { cut.removeLast() }
                data = Data(cut.utf8)
            }
            return (data, "txt", title(for: s))
        case .image(let png):
            guard !png.isEmpty, png.count <= maxImageBytes else { return nil }
            return (png, "png", "Image")
        }
    }

    static func digest(_ data: Data) -> String {
        SHA256.hash(data: data).prefix(16).map { String(format: "%02x", $0) }.joined()
    }

    private func entriesLocked(includeHidden: Bool) -> [URL] {
        let items = (try? FileManager.default.contentsOfDirectory(
            at: directory, includingPropertiesForKeys: [.contentModificationDateKey],
            options: includeHidden ? [] : [.skipsHiddenFiles])) ?? []
        return items.filter { includeHidden || !$0.lastPathComponent.hasPrefix(".") }
    }

    private func loadDigestsLocked() -> [String: String] {
        if let byDigest { return byDigest }
        var map: [String: String] = [:]
        for url in entriesLocked(includeHidden: false) {
            if let d = Self.readDigest(at: url) { map[d] = url.lastPathComponent }
        }
        byDigest = map
        return map
    }

    private func uniqueURLLocked(_ name: String) -> URL {
        let fm = FileManager.default
        var url = directory.appendingPathComponent(name)
        guard fm.fileExists(atPath: url.path) else { return url }
        let base = (name as NSString).deletingPathExtension, ext = (name as NSString).pathExtension
        var n = 2
        repeat {
            url = directory.appendingPathComponent("\(base) \(n).\(ext)")
            n += 1
        } while fm.fileExists(atPath: url.path)
        return url
    }

    private static func setDigest(_ digest: String, at url: URL) {
        _ = digest.withCString { value in
            setxattr(url.path, digestAttribute, value, strlen(value), 0, 0)
        }
    }

    static func readDigest(at url: URL) -> String? {
        var buf = [CChar](repeating: 0, count: 64)
        let n = getxattr(url.path, digestAttribute, &buf, buf.count - 1, 0, 0)
        guard n > 0 else { return nil }
        return String(decoding: buf.prefix(n).map { UInt8(bitPattern: $0) }, as: UTF8.self)
    }
}
