import Foundation
import MLX

// The cases that measure the machine's OWN corpus.
//
// PaperCasesCompute and PaperCasesStore answer "what is this mechanism worth", and to do that they
// need both arms on identical generated bytes. These cases answer a different question: what does
// this system cost on the files this person actually has, at their scale, on their hardware. The
// corpus is therefore not comparable between machines, and nothing here pretends otherwise - p13
// exports exactly what the corpus was, so every latency below is read against it.
//
// Two distinctions the bodies keep strictly:
//
//  - LATENCY IS A DISTRIBUTION, THROUGHPUT IS A RATE. A search box is judged by its tail, so query
//    and save cases keep every sample and emit p50/p95/p99 via PaperMetric.distribution (which
//    withholds p99 rather than compute one out of too few samples). A full indexing pass is a rate,
//    so p15 reports files/s and tokens/s and no percentile at all: per-file intervals inside a
//    batched pass are an artefact of the batch boundary, not a latency anyone waits for.
//  - READ-ONLY ON THE LIVE STORE. Query cases only read. The write-side cases stage a SAMPLE of
//    real files into the run's scratch directory and index those into a throwaway store, exactly as
//    runProfilingPass does. The user's own index is never written to.
public enum PaperCasesLive {

    public static func body(for id: PaperCaseID) -> PaperCaseBody? {
        switch id {
        case .p13_env: envBody
        case .p14_query: queryBody
        case .p15_index: indexBody
        case .p16_save: saveBody
        case .p17_tag: tagBody
        case .p18_liveshape: liveShapeBody
        default: nil
        }
    }

    /// Fixed query strings, identical on every machine and containing no user content, so a query
    /// latency is a property of the corpus and the hardware rather than of what was typed. Three
    /// lengths, because encode time follows token count and one length would report a single point
    /// of that curve as if it were the distribution.
    static let queryTexts: [String] = [
        "budget", "invoice", "red car", "meeting notes", "tax return",
        "screenshot of the login page", "quarterly revenue by region",
        "a photo taken at the beach in summer", "recipe with tomatoes and basil",
        "the contract clause about termination and notice periods",
        "diagram explaining how the system handles retries and backoff",
        "email thread about the office move scheduled for next quarter",
    ]

    // MARK: - p13 the corpus itself

    static let envBody: PaperCaseBody = { ctx in
        var out = PaperCaseOutput()
        guard let live = ctx.live else { out.note = noLive; return out }
        let snap = live.snapshot()
        out.metrics = [
            PaperMetric("files", runs: [Double(snap.files)], unit: .count, aggregate: .single),
            PaperMetric("chunks", runs: [Double(snap.chunks)], unit: .count, aggregate: .single),
            PaperMetric("index_size", runs: [Double(snap.indexBytes)], unit: .bytes, aggregate: .single),
        ]
        if snap.files > 0 {
            out.metrics.append(PaperMetric.derived("chunks_per_file",
                                                   value: Double(snap.chunks) / Double(snap.files),
                                                   unit: .count, from: ["chunks", "files"]))
        }
        // The modality mix, which is what makes every cross-modal row below readable.
        for kind in snap.kinds {
            out.metrics.append(PaperMetric("files_\(kind)", runs: [Double(live.store.fileCount(kind: kind))],
                                           unit: .count, aggregate: .single))
        }
        out.facts = [
            PaperFact("kinds", snap.kinds.joined(separator: "|")),
            PaperFact("ext_count", snap.exts.count),
            PaperFact("vector_dim", snap.vectorDim),
            PaperFact("index_model_variant", live.modelVariant),
            PaperFact("root_count", live.roots.count),
        ]
        return out
    }

    // MARK: - p14 what a query costs on that corpus

    static let queryBody: PaperCaseBody = { ctx in
        var out = PaperCaseOutput()
        guard let live = ctx.live else { out.note = noLive; return out }
        let snap = live.snapshot()
        guard snap.chunks > 0 else { out.note = "live index is empty"; return out }
        let p = ctx.params
        let textQueries = p.int("text_queries")
        let mediaQueries = p.int("media_queries")
        let topK = p.int("top_k")
        out.extraParameters = PaperParams([
            PaperParameter("live_chunks", .int(snap.chunks)),
            PaperParameter("live_files", .int(snap.files)),
        ])

        // The first query after the inter-case settle pays for the base fold and the first kernel
        // compile. That is a real cost the user sees once, so it is reported as its own number
        // rather than left to contaminate the distribution behind it.
        let cold = timeMs { _ = live.store.search(ctx.engine.embedQuery(queryTexts[0]), topK: topK, markActive: false) }
        out.metrics.append(PaperMetric("cold_first_query", runs: [cold], unit: .milliseconds, aggregate: .single,
                                       note: "first query after the inter-case settle, one sample"))
        for i in 0 ..< p.int("warmup_queries") {
            _ = live.store.search(ctx.engine.embedQuery(queryTexts[i % queryTexts.count]), topK: topK, markActive: false)
        }

        // TEXT -> anything: the shipped path, encode then search, split so the two halves can be
        // read separately (one is the encoder, the other is the corpus).
        var endToEnd: [Double] = [], encodeOnly: [Double] = [], scanOnly: [Double] = []
        for i in 0 ..< textQueries {
            try ctx.checkCancel()
            guard ctx.shouldContinue else { out.truncated = true; break }
            var v: [Float] = []
            let enc = timeMs { v = ctx.engine.embedQuery(queryTexts[i % queryTexts.count]) }
            let scan = timeMs { _ = live.store.search(v, topK: topK, markActive: false) }
            encodeOnly.append(enc); scanOnly.append(scan); endToEnd.append(enc + scan)
            if i % 25 == 0 { ctx.progress("text query \(i + 1)/\(textQueries)") }
        }
        out.metrics += PaperMetric.distribution("text_query", samples: endToEnd, unit: .milliseconds,
                                                note: "encode plus search, the shipped path")
        out.metrics += PaperMetric.distribution("text_encode", samples: encodeOnly, unit: .milliseconds)
        out.metrics += PaperMetric.distribution("text_scan", samples: scanOnly, unit: .milliseconds)

        // FILENAME: the same call with explicit filename intent, so the lexical channel answers at
        // full strength instead of being weighted by the shape heuristic.
        var filenameSamples: [Double] = []
        for i in 0 ..< textQueries where ctx.shouldContinue {
            let text = queryTexts[i % queryTexts.count]
            var f = SearchFilter(); f.filenameQuery = text
            let v = ctx.engine.embedQuery(text)
            filenameSamples.append(timeMs { _ = live.store.search(v, filter: f, topK: topK, markActive: false) })
        }
        out.metrics += PaperMetric.distribution("filename_query", samples: filenameSamples, unit: .milliseconds)

        // FIND SIMILAR: the pivot's vector is already stored, so this is scan and select with no
        // forward pass, which is the claim Section 3.4 makes for it.
        let pivots = livePaths(live, engine: ctx.engine, limit: p.int("pivot_files"), topK: topK)
        var similar: [Double] = []
        for i in 0 ..< textQueries where ctx.shouldContinue && !pivots.isEmpty {
            guard let v = live.store.fileVector(pivots[i % pivots.count]) else { continue }
            similar.append(timeMs { _ = live.store.search(v, topK: topK, markActive: false) })
        }
        out.metrics += PaperMetric.distribution("find_similar", samples: similar, unit: .milliseconds,
                                                note: "stored pivot vector, no forward pass")

        // IMAGE -> anything, AUDIO -> anything, VIDEO -> anything: a real file from the machine's
        // own roots as the query. Fewer samples than text, because each one decodes a file and runs
        // a tower; the distribution carries its own n so that is visible.
        let sampler = PaperFileSampler(roots: live.roots)
        for (label, kind) in [("image_query", FileKind.image), ("audio_query", FileKind.audio),
                              ("video_query", FileKind.video)] {
            guard ctx.shouldContinue else { break }
            if kind != .audio, !ctx.engine.supportsImages {
                out.facts.append(PaperFact("\(label)_status", "vision tower not resident"))
                continue
            }
            let files = sampler.sample(kinds: [kind], limit: max(1, mediaQueries / 4),
                                       shouldContinue: { ctx.shouldContinue })
            guard !files.isEmpty else {
                out.facts.append(PaperFact("\(label)_status", "no files of this kind under the roots"))
                continue
            }
            var samples: [Double] = []
            for i in 0 ..< mediaQueries {
                try ctx.checkCancel()
                guard ctx.shouldContinue else { out.truncated = true; break }
                var v: [Float]?
                let encode = timeMs { v = ctx.engine.embedFileQuery(files[i % files.count]) }
                guard let vec = v else { continue }
                let scan = timeMs { _ = live.store.search(vec, topK: topK, markActive: false) }
                samples.append(encode + scan)
                if i % 5 == 0 { ctx.progress("\(label) \(i + 1)/\(mediaQueries)") }
            }
            out.metrics += PaperMetric.distribution(label, samples: samples, unit: .milliseconds,
                                                    note: "decode plus encode plus search")
        }
        return out
    }

    // MARK: - p15 what a full indexing pass costs on real files

    static let indexBody: PaperCaseBody = { ctx in
        var out = PaperCaseOutput()
        guard let live = ctx.live else { out.note = noLive; return out }
        guard let staged = try stage(ctx, kinds: [.text], limit: ctx.params.int("files"),
                                     dir: "p15-real", out: &out) else { return out }

        let name = "p15-real.sqlite"
        let store = try ctx.fs.store(named: name)
        defer { ctx.fs.discard(store, named: name) }
        let indexer = Indexer(store: store, embedder: ctx.engine)

        // One pass over the staged tree through the shipped indexer, measured exactly as the
        // generated-corpus pass is, so the two are readable side by side.
        let pass = try PaperCasesCompute.runIndexPass(indexer: indexer, root: staged.dir,
                                                      settings: .paper, force: false,
                                                      label: "real files", ctx: ctx)
        out.truncated = pass.stoppedEarly
        let files = Double(pass.progress.embedded + pass.progress.unchanged)
        // Keys carry no unit word: the unit's own suffix supplies it, exactly as p03's
        // `fresh_files_per_s` does, so "real" plus .filesPerSecond reads real_files_per_s.
        if pass.wallSeconds > 0 {
            out.metrics += [
                PaperMetric("real", runs: [files / pass.wallSeconds], unit: .filesPerSecond, aggregate: .single),
                PaperMetric("real", runs: [Double(pass.tokens) / pass.wallSeconds],
                            unit: .tokensPerSecond, aggregate: .single),
                PaperMetric("real_gpu_busy", runs: [100 * pass.gpuBusySeconds / pass.wallSeconds],
                            unit: .percent, aggregate: .single),
            ]
        }
        out.metrics += [
            PaperMetric("files_indexed", runs: [files], unit: .count, aggregate: .single),
            PaperMetric("tokens", runs: [Double(pass.tokens)], unit: .count, aggregate: .single),
            PaperMetric("wall", runs: [pass.wallSeconds], unit: .seconds, aggregate: .single),
            PaperMetric("peak_gpu_delta", runs: [Double(pass.peakGPUDeltaBytes) / 1e6],
                        unit: .megabytes, aggregate: .single),
        ]
        out.facts.append(PaperFact("staged_bytes", staged.bytes))
        return out
    }

    // MARK: - p16 what one save costs, which is the cost that recurs

    static let saveBody: PaperCaseBody = { ctx in
        var out = PaperCaseOutput()
        guard let live = ctx.live else { out.note = noLive; return out }
        guard let staged = try stage(ctx, kinds: [.text], limit: ctx.params.int("files"),
                                     dir: "p16-real", minBytes: ctx.params.int("min_bytes"),
                                     out: &out) else { return out }

        for arm in ["cache_off", "cache_on"] {
            try ctx.checkCancel()
            guard ctx.shouldContinue else { out.truncated = true; break }
            out.arms.append(arm)
            try ctx.withArm(arm) {
                let name = "p16-\(arm).sqlite"
                let store = try ctx.fs.store(named: name)
                defer { ctx.fs.discard(store, named: name) }
                let indexer = Indexer(store: store, embedder: ctx.engine)
                // The index the edit lands on. Not timed: this is setup, and the measurement is the
                // save that follows it.
                indexer.index(roots: [staged.dir], settings: .paper, force: false) { _ in }

                var samples: [Double] = []
                for (i, url) in staged.files.enumerated() {
                    try ctx.checkCancel()
                    guard ctx.shouldContinue else { out.truncated = true; break }
                    guard let text = try? String(contentsOf: url, encoding: .utf8) else { continue }
                    let edited = text + "\nappended line for the save measurement\n"
                    guard (try? edited.write(to: url, atomically: true, encoding: .utf8)) != nil else { continue }
                    // update(paths:) IS the watcher path: one changed file, no crawl, exactly what
                    // the app runs when the user presses save.
                    samples.append(timeMs { indexer.update(paths: [url.path], settings: .paper) })
                    if i % 10 == 0 { ctx.progress("\(arm): save \(i + 1)/\(staged.files.count)") }
                }
                out.metrics += PaperMetric.distribution("save", samples: samples,
                                                        unit: .milliseconds, arm: arm,
                                                        note: "one edited file through the watcher path")
            }
        }
        // What reuse is worth on real files, at the median and at the tail.
        for suffix in ["p50", "p95", "p99"] {
            guard let off = out.metrics.first(where: { $0.key == "cache_off.save.\(suffix)" })?.value,
                  let on = out.metrics.first(where: { $0.key == "cache_on.save.\(suffix)" })?.value,
                  off > 0 else { continue }
            out.metrics.append(PaperMetric.derived("reuse_gain_\(suffix)", value: 100 * (off - on) / off,
                                                   unit: .percent,
                                                   from: ["cache_off.save.\(suffix)", "cache_on.save.\(suffix)"]))
        }
        return out
    }

    // MARK: - p17 tagging real images

    static let tagBody: PaperCaseBody = { ctx in
        var out = PaperCaseOutput()
        guard let live = ctx.live else { out.note = noLive; return out }
        guard let staged = try stage(ctx, kinds: [.image], limit: ctx.params.int("images"),
                                     dir: "p17-real", out: &out) else { return out }

        for arm in ["tags_off", "tags_on"] {
            try ctx.checkCancel()
            guard ctx.shouldContinue else { out.truncated = true; break }
            out.arms.append(arm)
            let name = "p17-\(arm).sqlite"
            let store = try ctx.fs.store(named: name)
            defer { ctx.fs.discard(store, named: name) }
            let indexer = Indexer(store: store, embedder: ctx.engine)
            var settings = IndexSettings.paperMedia
            settings.imageTags = (arm == "tags_on")

            var samples: [Double] = []
            for (i, url) in staged.files.enumerated() {
                try ctx.checkCancel()
                guard ctx.shouldContinue else { out.truncated = true; break }
                samples.append(timeMs { indexer.update(paths: [url.path], settings: settings, force: true) })
                if i % 4 == 0 { ctx.progress("\(arm): image \(i + 1)/\(staged.files.count)") }
            }
            out.metrics += PaperMetric.distribution("index_image", samples: samples,
                                                    unit: .milliseconds, arm: arm)
        }
        if let off = out.metrics.first(where: { $0.key == "tags_off.index_image.p50" })?.value,
           let on = out.metrics.first(where: { $0.key == "tags_on.index_image.p50" })?.value, off > 0 {
            out.metrics.append(PaperMetric.derived("tag_overhead_p50", value: 100 * (on - off) / off,
                                                   unit: .percent,
                                                   from: ["tags_off.index_image.p50", "tags_on.index_image.p50"]))
        }
        return out
    }

    // MARK: - p18 searching the real index while a real indexer runs

    static let liveShapeBody: PaperCaseBody = { ctx in
        var out = PaperCaseOutput()
        guard let live = ctx.live else { out.note = noLive; return out }
        let snap = live.snapshot()
        guard snap.chunks > 0 else { out.note = "live index is empty"; return out }
        let p = ctx.params
        let topK = p.int("top_k")
        let queries = p.int("queries")
        guard let staged = try stage(ctx, kinds: [.text], limit: p.int("load_files"),
                                     dir: "p18-real", out: &out) else { return out }
        out.extraParameters = PaperParams([
            PaperParameter("live_chunks", .int(snap.chunks)),
            PaperParameter("staged_files", .int(staged.files.count)),
        ])

        // The floor: the same query path against the same live store with nothing else on the
        // accelerator. Every loaded number below is read against this.
        var idle: [Double] = []
        for i in 0 ..< queries where ctx.shouldContinue {
            let v = ctx.engine.embedQuery(queryTexts[i % queryTexts.count])
            idle.append(timeMs { _ = live.store.search(v, topK: topK, markActive: false) })
        }
        out.metrics += PaperMetric.distribution("idle", samples: idle, unit: .milliseconds,
                                                note: "the live index, no indexer running")

        for arm in ["unshaped", "shaped"] {
            try ctx.checkCancel()
            guard ctx.shouldContinue else { out.truncated = true; break }
            out.arms.append(arm)
            try ctx.withArm(arm) {
                let name = "p18-\(arm).sqlite"
                let store = try ctx.fs.store(named: name)
                defer { ctx.fs.discard(store, named: name) }
                let indexer = Indexer(store: store, embedder: ctx.engine)

                // A real indexing load on real files, on its own thread, while the queries go to
                // the LIVE store. Both reach the same accelerator through the same gate, which is
                // the contention the mechanism exists for.
                let stop = PaperFlag()
                let done = DispatchSemaphore(value: 0)
                let paths = staged.files.map(\.path)
                DispatchQueue.global(qos: .utility).async {
                    while !stop.isOn {
                        indexer.update(paths: paths, settings: .paper, force: true)
                    }
                    done.signal()
                }
                defer { stop.turnOn(); indexer.cancel(); done.wait(); indexer.resetCancelled() }

                var samples: [Double] = []
                for i in 0 ..< queries {
                    try ctx.checkCancel()
                    guard ctx.shouldContinue else { out.truncated = true; break }
                    // The keystroke that precedes the query by the debounce interval is what arms
                    // the mechanism. Without it the shaped arm has nothing to act on and both arms
                    // would measure the same thing.
                    ctx.engine.noteInteractive()
                    Thread.sleep(forTimeInterval: p.double("debounce_s"))
                    let v = ctx.engine.embedQuery(queryTexts[i % queryTexts.count])
                    samples.append(timeMs { _ = live.store.search(v, topK: topK, markActive: true) })
                    if i % 10 == 0 { ctx.progress("\(arm): query \(i + 1)/\(queries)") }
                }
                out.metrics += PaperMetric.distribution("loaded", samples: samples,
                                                        unit: .milliseconds, arm: arm)
            }
        }
        for suffix in ["p50", "p95", "p99"] {
            guard let off = out.metrics.first(where: { $0.key == "unshaped.loaded.\(suffix)" })?.value,
                  let on = out.metrics.first(where: { $0.key == "shaped.loaded.\(suffix)" })?.value,
                  off > 0 else { continue }
            out.metrics.append(PaperMetric.derived("shaping_gain_\(suffix)", value: 100 * (off - on) / off,
                                                   unit: .percent,
                                                   from: ["unshaped.loaded.\(suffix)", "shaped.loaded.\(suffix)"]))
        }
        return out
    }

    // MARK: - shared helpers

    static let noLive = "no live index: this build ran outside the app, or no index exists yet"

    struct StagedSample {
        let dir: URL
        let files: [URL]
        let bytes: Int
    }

    /// Sample real files of the given kinds, copy them into the run's scratch directory, and report
    /// what was staged. Returns nil (with `out.note` set) when the machine has nothing of that kind,
    /// which is a legitimate outcome on a corpus without audio or without images.
    static func stage(_ ctx: PaperContext, kinds: Set<FileKind>, limit: Int, dir: String,
                      minBytes: Int = 1_024, out: inout PaperCaseOutput) throws -> StagedSample? {
        guard let live = ctx.live else { out.note = noLive; return nil }
        ctx.progress("sampling real files")
        let picked = PaperFileSampler(roots: live.roots)
            .sample(kinds: kinds, limit: limit, minBytes: minBytes,
                    shouldContinue: { ctx.shouldContinue })
        guard !picked.isEmpty else {
            out.note = "no files of kind \(kinds.map(\.rawValue).sorted().joined(separator: "|")) under the roots"
            return nil
        }
        let root = try ctx.fs.scratch(named: dir)
        let staged = try paperStageRealFiles(picked, into: root)
        guard !staged.isEmpty else { out.note = "no real file could be staged"; return nil }
        let bytes = staged.reduce(0) { sum, u in
            sum + ((try? FileManager.default.attributesOfItem(atPath: u.path)[.size] as? Int) ?? 0 ?? 0)
        }
        out.extraParameters = out.extraParameters.merging(
            PaperParams([PaperParameter("staged_files", .int(staged.count))]))
        return StagedSample(dir: root, files: staged, bytes: bytes)
    }

    /// Elapsed wall time of `body`, in milliseconds.
    static func timeMs(_ body: () -> Void) -> Double {
        let t = Date()
        body()
        return -t.timeIntervalSinceNow * 1000
    }

    /// Indexed paths, taken from what queries answer rather than from a private table. Used only to
    /// pick find-similar pivots inside the process; no path reaches the export.
    static func livePaths(_ live: PaperLiveIndex, engine: OmniEngine, limit: Int, topK: Int) -> [String] {
        guard limit > 0 else { return [] }
        var seen: [String] = []
        for text in queryTexts {
            for h in live.store.search(engine.embedQuery(text), topK: topK, markActive: false)
            where !seen.contains(h.path) {
                seen.append(h.path)
                if seen.count >= limit { return seen }
            }
        }
        return seen
    }
}

/// A cancel flag shared with the background indexing load: the writer is the case body and the
/// reader is another thread, so it is lock-guarded exactly as the app's CancelFlag is.
final class PaperFlag: @unchecked Sendable {
    private let lock = NSLock()
    private var on = false
    var isOn: Bool { lock.lock(); defer { lock.unlock() }; return on }
    func turnOn() { lock.lock(); on = true; lock.unlock() }
}
